// Datos completos del sitio - Turismo Rural Maimará
window.SITE_DATA = {
  brand: { name: "Turismo Rural Maimará", tagline_es: "Viví la Quebrada desde adentro", tagline_en: "Live the Quebrada from within" },

  emprendimientos: [
    {
      id: "intipacha", nombre: "Inti Pacha", sub: "Casa de infusiones y productos artesanales",
      anfitriones: ["Solange Morales", "Alberto Castagnolo"],
      ubicacion: "Pasaje 2 de Febrero, Barrio Matadero, Maimará. Es un pasaje semicircular al que se llega por calles Padre Lázaro o Colombres Garmendia, cerca de San Martín. Queda a unas cuadras de la Oficina de Información Turística.",
      categorias: ["gastronomia", "huerta", "sustentabilidad"], color: "#5C7A3F", colorAccent: "#D9892A", numero: "01",
      bio: "Intipacha es un espacio familiar en Maimará, Quebrada de Humahuaca, donde compartimos nuestra forma de vivir y entender este lugar. El nombre lo dice todo: Inti (sol) y Pacha (entorno, tierra) son los pilares de lo que hacemos, siempre en armonía con la naturaleza, la historia y la gente que habita la quebrada.",
      historia: "En plena pandemia, 2020, nos animamos a emprender. Ya queríamos tener una huerta, así que preparamos el fondo, plantamos aromáticas y especias. Después, con materiales reciclados, armamos deshidratadores caseros y empezamos a producir para vender. También dulces y panes. Todo muy casero, muy de a poco. Hoy seguimos así: cuidando la tierra, valorando lo nuestro y compartiendo experiencias con quienes se acercan.",
      anfitrionBios: [
        { nombre: "Solange Morales", texto: "Nací en San Pedro de Jujuy, crecí en Palmasola, en las Yungas, rodeada de montañas, cítricos y ganado. A cocinar aprendí desde chica con mi mamá y mi abuela, pero recién cuando me fui a vivir sola, como por el 2010, empecé a explorar la cocina en profundidad. Hace unos años estudié la Tecnicatura en Cocinas Regionales y Cultura Alimentaria, y también una Diplomatura en Cultivos Andinos. Todo eso hoy lo vuelco en Intipacha." },
        { nombre: "Alberto Castagnolo", texto: "Nací en Salta, pero crecí en San Salvador de Jujuy. Trabajo en turismo desde hace más de quince años. Acompañé las primeras experiencias en Turismo Rural desde la Secretaría de Turismo de la Provincia, después fui Secretario de Turismo y Cultura en Purmamarca y Director de Turismo en Tumbaya. En 2017 me vine a vivir a Maimará, a mi casa familiar de vacaciones de la infancia, y acá empezó esta nueva etapa junto a Sol." }
      ],
      ofrecemos: [
        { titulo: "Turismo rural y cultural", desc: "Experiencias sencillas pero con mucho sentido: conocer nuestra huerta, cocinar con productos locales, charlar sobre los saberes que se transmiten de generación en generación. Lo que mostramos es lo que vivimos." },
        { titulo: "Gastronomía con productos de la tierra", desc: "Cocinamos con ingredientes andinos, harinas alternativas, verduras de nuestra huerta. Respetamos los tiempos de la tierra y tratamos de que cada plato sea una forma de conocer la Quebrada desde adentro." },
        { titulo: "Compromiso con el entorno", desc: "Para nosotros, reciclar es un hábito de toda la vida. Usamos materiales reutilizados, compostamos, intercambiamos recursos con los vecinos. Producimos a pequeña escala, sin forzar la tierra ni las cosas." },
        { titulo: "Trabajo con la comunidad", desc: "Creemos en hacer camino junto a otros. Por eso trabajamos con productores, artesanos y emprendedores de la zona." }
      ],
      contacto: { instagram: "@intipacha_maimara" }, pagos: "Efectivo y transferencia.",
      horarios: "Actividades: sábados, domingos y feriados de 17 a 20 h. Venta de productos (dulces, especias, aromáticas deshidratadas): otros días, pero siempre mejor mandar un mensaje antes para asegurarse de que estamos.",
      sello: "Sello Cocinar — Ministerio de Turismo de la Nación. También formamos parte de Asociación de Turismo de Quebrada y Puna.",
      imgRetrato: "images/retratoIntiPacha.jpeg", imgDet1: "images/intipacha/intiPacha1.jpeg", imgDet2: "images/intipacha/intiPacha2.jpeg",
    },
    {
      id: "estrella", nombre: "La Estrella Familiar", sub: "Experiencias rurales con anfitriona",
      anfitriones: ["Ramona Rodríguez"],
      ubicacion: "Calle Belgrano, Barrio San Francisco, Maimará. Es una zona serena, donde el agua recorre los canales y acequias, irrigando los terrenos y quintas pobladas de molles. La forma más práctica de llegar es por el acceso norte (calle Bernardino Rivadavia). Estamos solo a tres cuadras de la intersección de Belgrano y Rivadavia.",
      categorias: ["rural", "animales", "huerta", "gastronomia"], color: "#C5483A", colorAccent: "#E8B23F", numero: "02",
      bio: "La Estrella Familiar nació de la hospitalidad sencilla y genuina que caracteriza a los habitantes de Maimará. Todo comenzó alojando a amigos y simpatizantes de una comparsa local. Hoy, es una casa que abre sus puertas y su rutina para compartir una experiencia auténtica: la vida cotidiana de una familia que, como muchas otras en la Quebrada, trabaja la tierra y cría animales. Con Ramona y su familia, serás un visitante que participará en las tareas del día a día: ayudarás en el pastoreo de las cabras, aprenderás los secretos de la elaboración artesanal del queso, cuidarás la huerta y las gallinas. Cada actividad termina compartiendo la mesa, con los sabores puros y directos de lo que producimos.",
      historia: "Soy Ramona Rodríguez. Mi historia está profundamente enraizada en esta tierra. Nací en el Pucará de Tilcara y crecí entre los cerros de Maimará y Huichaira, acompañando a mi madre en sus labores de campo. De ella, la persona más trabajadora que he conocido, aprendí a criar cabras, a sembrar maíz y papas, y a seleccionar los mejores frutos. Mi vida profesional me llevó a conocer y vivir en pueblitos de la Puna Jujeña, pero en 2017 mi corazón me guió de vuelta a Maimará. Abrí por primera vez las puertas de mi casa un Carnaval, allá por 2018. Como yo tenía unas habitaciones disponibles, decidí acondicionarlas y recibí a mis primeros huéspedes. Desde ese entonces cada vez que albergamos a alguien lo integramos a nuestra vida y nuestra casa como alguien que llega de visita.",
      anfitrionBios: [{ nombre: "Ramona Rodríguez", texto: "Hoy me dedico a lo que más me gusta: pastorear y cuidar de mis cabras, elaborar quesos con su leche, y cultivar la tierra para llenar la mesa de mi familia con los colores y sabores de nuestra huerta." }],
      ofrecemos: [
        { titulo: "Animales del campo", desc: "Alimentar y mimar a nuestros animales (las traviesas cabras, las gallinas y nuestros fieles perros)." },
        { titulo: "Labores agrícolas", desc: "Participar en las labores agrícolas, sintiendo la tierra entre tus manos." },
        { titulo: "Cocina y mesa compartida", desc: "Colaborar en tareas domésticas tradicionales, como preparar una receta local llena de sabor e historia." }
      ],
      contacto: { whatsapp: "+54 9 3884 78-4785", instagram: "@ramor5243", facebook: "ramo.rodri.2025" },
      pagos: "Solamente transferencia y efectivo. Poseemos internet en nuestro emprendimiento.",
      horarios: "Solo con reserva. Para vivir esta experiencia, puede realizar su reserva vía WhatsApp, hasta el día anterior a las 20:00 horas.",
      imgRetrato: "images/retratoRamona.jpeg", imgDet1: "images/estrellafamiliar/estrellafamiliar1.jpeg", imgDet2: "images/estrellafamiliar/estrellafamiliar2.jpeg",
    },
    {
      id: "manitos", nombre: "Manitos Tejedoras", sub: "Tradición textil andina viva",
      anfitriones: ["Ortencia Quispe"],
      ubicacion: "Calle Muña Muña, entre calles Sumalagua y San Cayetano, Barrio Sumaj Pacha (entre Maimará y Tilcara). Punto de venta en la plaza central de Tilcara, frente a calle Rivadavia. Las experiencias se realizan en mi casa y taller.",
      categorias: ["textil", "artesania", "tradicion"], color: "#6B3F7B", colorAccent: "#1F8A8A", numero: "03",
      bio: "Manitos Tejedoras es un emprendimiento familiar donde la tradición textil andina cobra vida. Constituye un puente entre el legado ancestral y el mundo contemporáneo. Desde la meticulosa selección de los cueros de llama y oveja —que son conservados con esmero— hasta la transformación final en prendas únicas, la artesana Ortencia guía cada etapa con el conocimiento profundo de quien ha dedicado su vida a este oficio. Como guardiana de técnicas ancestrales, Ortencia domina el arte del teñido con pigmentos naturales y el hilado en puisca, el huso prehispánico que da vida a cada hebra.",
      historia: "Soy Ortencia Quispe, nacida en Rodeo Colorado, departamento de Iruya. Crecí en una familia que criaba ovejas, muchas ovejas, y transformaba su lana en hermosos ponchos. Aprendí a hilar desde muy pequeña, y siempre fue la parte de todo el proceso que más me gustó. Aún siendo muy chiquita, hacía bailar mi puisca, hecha con una ramita de chilca, y me guardaba pequeños retazos de lana para poder practicar. A los 21 años me trasladé a la Quebrada de Humahuaca. Dejé mis ovejas en el cerro y me instalé en Tilcara. Aunque cambié de paisaje, nunca dejé de transformar la lana en prendas, manteniendo viva la tradición heredada.",
      anfitrionBios: [{ nombre: "Ortencia Quispe", texto: "Hoy abrimos las puertas de nuestra casa para compartir con ustedes los saberes ancestrales de la lana: desde el hilado hasta el tejido, transmitiendo no solo una técnica, sino una historia de vida." }],
      ofrecemos: [
        { titulo: "Hilado en puisca", desc: "El huso prehispánico que da vida a cada hebra." },
        { titulo: "Teñido natural", desc: "Pigmentos de plantas y minerales recolectados en la quebrada." },
        { titulo: "Tejido en telar bastidor", desc: "Las primeras tramas con tus propias manos." }
      ],
      contacto: { whatsapp: "+54 9 3884 15-8833", instagram: "@manitostejedoras" },
      pagos: "Tarjetas de débito y crédito, transferencias bancarias. Contamos con medios de pago electrónicos e internet en el taller.",
      horarios: "Para experiencias: 10:00 a 12:00 hs (mañana) y 15:00 a 17:00 hs (tarde). Fuera de estos horarios pueden aproximarse a comprar prendas y suvenires textiles que siempre tengo en stock, tanto a mi taller como a mi puesto en la plaza central de Tilcara.",
      imgRetrato: "images/retratoOrtencia.jpeg", imgDet1: "images/manitostejedoras/manitostejedoras1.jpeg", imgDet2: "images/manitostejedoras/manitostejedoras2.jpg",
    },
    {
      id: "qullana", nombre: "Qulläna", sub: "Plantas medicinales y alquimia vegetal",
      anfitriones: ["Marina"],
      ubicacion: "🔨 Experiencias (El Taller): Pasaje 19 de abril (final), Barrio El Cristo. A pasos del acceso sur a Maimará. Aquí creamos, no siempre hay stock para la venta directa. 🛒 Comprar (Punto de Venta): Hostería La Paleta del Pintor. Alvarez Parado 1468 esq. Cornelio Zelaya.",
      categorias: ["herbolaria", "sustentabilidad", "taller"], color: "#1F8A8A", colorAccent: "#5C7A3F", numero: "04",
      bio: "«Qulläna» es una iniciativa que nace luego de nueve años de contacto con la tierra y las plantas medicinales. Elegimos este nombre porque la Qulläna o Qullaña (en lengua aimara) hace alusión a la salud y significa «el que cura». La qullaña o sanar aimara, incorpora la salud mental, espiritual y física de los individuos, de la comunidad misma, y la relación de la colectividad y del individuo con la Madre Tierra. La qullaña trasciende más allá de la cura de una enfermedad, y está fuertemente vinculada con el territorio, la lengua, la comunidad, el respeto a la Madre Tierra, los conocimientos tradicionales y la identidad.",
      historia: "Mi nombre es Marina, nací en la provincia de Buenos Aires, en la zona norte, muy cerca del Delta del Tigre. Estudié la carrera de Turismo con especialización en sustentabilidad. Al terminar mis estudios, emprendí un viaje por Latinoamérica que duró diez años: desde Tierra del Fuego hasta México. Viví en Perú, Ecuador, Colombia, Venezuela, Panamá, Costa Rica. Siempre me he establecido en zonas rurales, trabajando y aprendiendo de los agricultores. Los últimos cuatro años antes de regresar a la Argentina, en 2019, viví en México. Fue entonces donde aprendí a destilar aceites esenciales, a preparar cremas, pomadas y tinturas madre. Qulläna nació en pandemia, un momento que nos obligó a quedarnos en un lugar.",
      anfitrionBios: [{ nombre: "Marina", texto: "Compré mi primer destilador de plantas y comencé a experimentar. Como no tenía espacio propio, una familia del pueblo me ha brindado muy generosamente un espacio en su tierra, lo que me permitió entender que no hace falta tener un lugar propio para cultivar, sino que se puede trabajar en comunidad." }],
      ofrecemos: [
        { titulo: "Destilación por arrastre de vapor", desc: "Aceites esenciales e hidrolatos extraídos en alambique artesanal." },
        { titulo: "Pomadas y tinturas madre", desc: "Medicina familiar con plantas, ceras y aceites." },
        { titulo: "Showroom de productos", desc: "Punto de venta en Hostería La Paleta del Pintor." }
      ],
      contacto: { whatsapp: "+54 9 11 3034 1946", instagram: "@qullana_argentina", facebook: "qüllanaremediosnaturales" },
      pagos: "Efectivo, transferencia bancaria, QR, tarjeta de crédito o débito.",
      horarios: "Para experiencias: 10:00 a 13:00 hs (mañana) y 15:00 a 18:00 hs (tarde). Con reserva previa (mínimo 48 hs). Fuera de estos horarios pueden aproximarse a comprar productos en la tienda ubicada en Hostería La Paleta del Pintor, de 9 a 20 hs.",
      imgRetrato: "images/retratoMarina.jpeg", imgDet1: "images/qullana/qullana1.jpeg", imgDet2: "images/qullana/qullana2.jpeg",
    },
    {
      id: "alborada", nombre: "Tejidos Alborada", sub: "Saberes textiles de la Puna jujeña",
      anfitriones: ["Nora Quispe"],
      ubicacion: "Calle Pedro Manzur, Barrio Güemes, Maimará, muy cerca de la entrada al cementerio Nuestra Señora del Carmen. Brindo mis servicios por lo general allí, aunque también ofrezco la posibilidad de realizar las experiencias en otros espacios como alojamientos o centros culturales de Maimará o de localidades vecinas como Tilcara o Purmamarca.",
      categorias: ["textil", "artesania", "bordado"], color: "#D9892A", colorAccent: "#C5483A", numero: "05",
      bio: "Tejidos Alborada es un espacio textil donde los saberes ancestrales de la Puna jujeña cobran vida. Más que un taller, es un legado vivo: aquí, Nora —descendiente de un extenso linaje de tejedores— entrelaza la herencia de sus ancestros en cada hilo y bordado. En este lugar no solo se crean prendas; se preservan historias, se honra a los antepasados y se comparten secretos milenarios con quienes deseen conectar con el alma auténtica de los Andes. Es una experiencia para quienes buscan llevarse a casa algo más que un recuerdo: un fragmento de una añeja tradición.",
      historia: "Soy Nora Quispe, artesana textil y bordadora. Nací en Coranzulí, un pequeño pueblo en el corazón de la Puna jujeña. Pertenezco a un extenso linaje de tejedores que me heredaron este oficio. Aprendí a tejer a mis 10 años de la mano de mi madre. Ya de adulta, me incorporé con ella a una cooperativa pionera en el aprovechamiento de la fibra de llama, allá por los años noventa. Hace más de dos décadas me radiqué en Maimará, donde vivo con mis cuatro hijos. Durante mucho tiempo confeccioné prendas y souvenirs para tiendas de Purmamarca, pero siempre guardé un anhelo: poder conectar directamente con las personas que valoran mi trabajo, contarles las historias de mi familia y de mi vida.",
      anfitrionBios: [{ nombre: "Nora Quispe", texto: "Motivada por la alegría de compartir saberes, y sobre todo por el profundo deseo de que mi autoría sea reconocida, decidí crear este emprendimiento y esta experiencia. Hoy, cada pieza que nace aquí lleva no solo mi técnica, sino también mi historia y mi nombre." }],
      ofrecemos: [
        { titulo: "Bordado de flores", desc: "El sello personal de Nora: flores coloridas con técnicas heredadas." },
        { titulo: "Adornos con flores de lana", desc: "Recreamos la tradición de «florar» el ganado de la Puna." },
        { titulo: "Circuito del textil", desc: "Cuatro estaciones desde la fibra hasta la prenda terminada." }
      ],
      contacto: { whatsapp: "+54 9 388 472873", instagram: "@tejidosalborada", facebook: "tejidosalborada" },
      pagos: "Tejidos Alborada posee medios de pago electrónicos e internet en su local.",
      horarios: "Los horarios recomendados para realizar las actividades son de 10:00 a 12:00 hs por la mañana y de 15:00 a 17:00 hs por la tarde. Fuera de estos horarios pueden aproximarse a comprar prendas y suvenires textiles que siempre tengo en stock.",
      imgRetrato: "images/retratoNora.jpeg", imgDet1: "images/alborada/alborada1.jpeg", imgDet2: "images/alborada/alborada2.jpeg",
    },
    {
      id: "tierramia", nombre: "Tierra Mía", sub: "Cultivo de flores y hortalizas",
      anfitriones: ["Patricia Cruz"],
      ubicacion: "Los sembradíos de Tierra Mía se encuentran al final de la calle Coronel Zelaya, en su intersección con la Avenida Froilán Calvetti o Costanera, al pie de la colorida Paleta del Pintor.",
      categorias: ["agricola", "huerta", "rural"], color: "#A03A52", colorAccent: "#5C7A3F", numero: "06",
      bio: "Tierra Mía es una experiencia auténtica de conexión con la tierra, centrada en el cultivo de flores y hortalizas, guiada por su propia productora. Doña Patricia y su familia llevan más de 30 años dedicados a las actividades agrícolas en un pequeño predio situado al pie de la Paleta del Pintor. En Tierra Mía no solo observará un campo, sino que se familiarizará con la vida del agricultor en Maimará. Conocerá de primera mano sus ritmos y ciclos naturales, y descubrirá las estrategias de diversificación y las prácticas tradicionales que aplican para la conservación del suelo, el tesoro más preciado que les permite un sustento sostenible en este entorno único.",
      historia: "Me llamo Patricia Cruz. Nací en Uquía y hoy vivo en Maimará. Hace más de 30 años, mi actividad se limitaba a las hortalizas. Fue mi vecino, don Juan Antonio Cruz —un reconocido productor de flores y director de la Escuela Técnica— quien vio en mí algo más. Él me insistía: «Vos, Patricia, tenés que hacer flores». Como yo no tenía idea, un buen día llegó con las semillas y me dijo: «Te traje esto para que pongas flores». Con mi marido, empezamos con 20 surcos. Hoy, aquella semilla que dudé en plantar floreció en un emprendimiento sólido. Cultivo casi 15 variedades de flores, un proceso delicado que lleva unos 8 meses desde la semilla hasta la producción.",
      anfitrionBios: [{ nombre: "Patricia Cruz", texto: "Me dedico al cultivo de flores y hortalizas, que es mi sustento… y también soy guía en mi propio emprendimiento, una actividad que me encanta porque me permite desconectarme, charlar con gente nueva y vivir otras experiencias." }],
      ofrecemos: [
        { titulo: "Visita al campo de flores", desc: "Recorrido por parcelas en distintas etapas de crecimiento." },
        { titulo: "Saberes agroecológicos", desc: "Rotación de cultivos, abonadas, cuidados contra hongos y ácaros." },
        { titulo: "Historias de familia", desc: "Cosechamos hermosos recuerdos junto a las plantaciones." }
      ],
      contacto: { instagram: "@turismoruralmaimara" },
      pagos: "Puede realizar pagos, tanto para compra de flores como para las visitas, mediante transferencia o en efectivo.",
      horarios: "Los horarios recomendados para realizar las actividades son de 10:00 a 12:00 hs por la mañana y de 16:00 a 19:00 hs por la tarde. Fuera de estos horarios pueden aproximarse a comprar flores a la quinta ubicada en la intersección de las calles Cornelio Zelaya y Froilán Calvetti.",
      imgRetrato: "images/retratoPatricia.jpeg", imgDet1: "images/tierramia/tierramia1.jpeg", imgDet2: "images/tierramia/tierramia2.jpeg",
    }
  ],

  experiencias: [
    {
      id: "ip-1", emprendimiento: "intipacha",
      titulo: "Recorrido por nuestras prácticas ambientales",
      subtitulo: "Una experiencia de vida sostenible en IntiPacha",
      duracion: "1 hora aprox.", grupo: "De 2 a 15 personas", dificultad: "Bajo", categoria: "sustentabilidad",
      descripcion: "El cuidado de nuestra Pacha es un pilar en nuestra vida cotidiana. En nuestro hogar y emprendimiento hemos sistematizado 12 prácticas ambientales que aplicamos día a día y que nos encanta compartir con quienes nos visitan.\n\nContamos con una pequeña pero variada huerta agroecológica donde cultivamos plantas aromáticas y especias, utilizamos deshidratadores construidos con materiales reciclados y desarrollamos múltiples acciones concretas que reflejan nuestro compromiso con el cuidado del entorno.\n\nEsta experiencia propone un acercamiento cercano, didáctico y vivencial a nuestra forma de habitar el territorio.",
      queHaremos: "Los recibiremos con calidez en nuestro espacio y les presentaremos nuestra pequeña, pero variada y vistosa huerta agroecológica. Conversaremos sobre cultivos andinos, plantas aromáticas y sobre la manera en que trabajamos la tierra sin utilizar químicos.\n\nRealizaremos un recorrido guiado por la huerta y la casa, compartiendo nuestras prácticas ambientales, que constituyen el corazón de nuestro estilo de vida y de IntiPacha.\n\nCerraremos la experiencia compartiendo una bebida tradicional —caliente o refrescante, según la temporada— y cada visitante se llevará como recuerdo un pequeño sobre con aromáticas de nuestra huerta.",
      incluye: ["Una bebida tradicional caliente o refrescante.", "Souvenir: Un sobre con aromáticas."],
      dificultadDetalle: "Bajo. Pueden realizar esta actividad todas aquellas personas que tengan interés en familiarizarse con prácticas ambientales cotidianas de un hogar. Es pertinente aclarar que nuestra casa posee amplios desniveles y que el ingreso a la misma y a la huerta, posee escalones.",
      img: "images/intipacha/ambiental1.jpeg", imgGal1: "images/intipacha/ambiental2.jpeg", imgGal2: "images/intipacha/ambiental3.jpeg", imgGal3: "images/intipacha/ambiental4.jpeg",
    },
    {
      id: "ip-2", emprendimiento: "intipacha",
      titulo: "Sabores conscientes en ollas de barro",
      subtitulo: "Merienda con panes e infusiones caseros",
      duracion: "1 hora y 30 minutos", grupo: "De 1 a 8 personas por grupo", dificultad: "Bajo", categoria: "gastronomia",
      descripcion: "Los dulces elaborados con frutas de estación en ollas de barro, las hierbas aromáticas y los diversos panificados artesanales fueron de los primeros y más significativos productos de IntiPacha. Esta experiencia nace del deseo de compartir cómo los elaboramos y de abrir nuestro comedor para ofrecer un momento de pausa, abrigo y encuentro con los sabores de la región.\n\nDurante una hora y media, el aroma de las hierbas recién infusionadas acompaña el compartir de panes artesanales y dulces caseros. Cada preparación respeta los tiempos de la naturaleza y refleja nuestros cuidados, nuestra manera de habitar la tierra y el vínculo profundo que sostenemos con el territorio.\n\nLa experiencia transcurre en un ambiente íntimo y familiar, donde la conversación fluye con naturalidad. Es una invitación a detenerse, saborear y sentirse parte.",
      queHaremos: "Antes de su llegada nos comunicaremos para compartir los detalles y coordinar el encuentro. Una vez en casa, les daremos la bienvenida e invitaremos a recorrer nuestra huerta orgánica, donde cultivamos especias y aromáticas que utilizamos en nuestras preparaciones y deshidratamos para la venta.\n\nLuego presentaremos nuestros productos y los procesos de reciclaje que implementamos en su elaboración. Mientras finalizamos los preparativos, compartiremos material bibliográfico y audiovisual sobre hechos y manifestaciones culturales de nuestra provincia.\n\nCerraremos el encuentro con una merienda abundante que incluye infusiones de hierbas andinas, panes artesanales, muffins, alfajores de harina de habas, queso de cabra y dulces de frutas de estación preparados por nosotros en ollas de barro.",
      incluye: ["Merienda al finalizar la actividad (infusiones con aromáticas de nuestra huerta, panes y dulces caseros)."],
      dificultadDetalle: "Actividad de baja dificultad, apta para todas aquellas personas interesadas en conocer las prácticas cotidianas de un emprendimiento familiar de turismo rural con enfoque de triple impacto. También es ideal para quienes deseen degustar productos caseros elaborados con ingredientes de la región. Es importante tener en cuenta que la casa presenta amplios desniveles y que el acceso tanto a la vivienda como a la huerta incluye escalones.",
      img: "images/intipacha/ollas1.jpeg", imgGal1: "images/intipacha/ollas2.jpeg", imgGal2: "images/intipacha/ollas3.jpeg", imgGal3: "images/intipacha/ollas4.jpeg",
    },
    {
      id: "ip-3", emprendimiento: "intipacha",
      titulo: "Aromas, sabores y secretos de la cocina familiar andina",
      subtitulo: "Cocina participativa",
      duracion: "3 horas", grupo: "De 2 a 6 personas", dificultad: "Bajo", categoria: "gastronomia",
      descripcion: "Compartir la mesa es, para nosotros, un ritual sagrado que tradicionalmente se reserva a los vínculos más cercanos. En nuestra cultura, no es solo sentarse a comer: es confiar, es abrir el círculo, es decir «sos parte».\n\nEn IntiPacha elegimos abrir ese espacio con respeto y generosidad, movidos por la vocación profunda de compartir con quienes desean acercarse a nuestra cultura y, especialmente, a nuestra cultura alimentaria.\n\nLos platos que llevamos a la mesa son los que nos acompañan en nuestra vida cotidiana: propios de esta tierra, respetuosos de sus tiempos y portadores de la memoria de quienes nos enseñaron a cocinar. Cada preparación es una conversación con el territorio.\n\nAbrir la mesa es abrir el corazón. Y quien se sienta en ella deja de ser visitante para convertirse, aunque sea por un momento, en parte viva de nuestra historia.",
      queHaremos: "Previo a su llegada, nos comunicaremos para compartir los detalles de la experiencia. Les enviaremos nuestra carta para que puedan seleccionar las opciones de bebida, entrada, plato principal y postre, teniendo en cuenta que el plato principal será elaborado junto a nosotros.\n\nAl recibirlos en casa les daremos la bienvenida y, si lo desean, podrán visitar la huerta para reconocer los productos que utilizaremos en la preparación. Luego nos equiparemos e iniciaremos la elaboración del plato principal, según la temporada, mientras compartimos técnicas tradicionales y el uso de utensilios típicos de la cocina andina.\n\nDurante el proceso abriremos un espacio de conversación sobre cultura alimentaria andina, costumbres y relatos familiares. Cerraremos la experiencia degustando el menú completo, compartiendo la mesa en un ambiente cálido y familiar.",
      incluye: ["Menú de 4 pasos (bebida, entrada, plato principal y postre).", "Elaboración participativa del plato principal.", "Todos los ingredientes y utensilios de cocina.", "Degustación del menú completo."],
      dificultadDetalle: "Bajo. Actividad pensada para personas que disfrutan cocinar, valoran lo producido en casa o tienen interés en prácticas ecológicas. No se requiere experiencia previa, ya que acompañamos cada paso del proceso. Está orientada principalmente a adolescentes y adultos. En caso de asistir con niños, podemos proponer actividades en la huerta o juegos didácticos. Es una experiencia apta para personas celíacas y diabéticas (previa coordinación). El acceso a la casa presenta escalones y un pasillo angosto.",
      img: "images/intipacha/cocina1.jpeg", imgGal1: "images/intipacha/cocina2.jpeg", imgGal2: "images/intipacha/cocina3.jpeg", imgGal3: "images/intipacha/cocina4.jpeg",
    },

    {
      id: "es-1", emprendimiento: "estrella",
      titulo: "Mañanas de Campo", subtitulo: "Vida rural junto a Ramona",
      duracion: "De 10:00 a 12:00 hs aprox.", grupo: "De 1 a 6 personas", dificultad: "Bajo", categoria: "rural",
      descripcion: "Les invitamos a conocer nuestra casa y compartir con nosotros las tareas de todos los días. Vivimos de la tierra: tenemos una huerta, cabras y gallinas. Con la leche de las cabras hacemos nuestros propios quesos, y los huevos de las gallinas son los que llegan frescos a la mesa.\n\nNo hace falta que sepan de campo ni que tengan experiencia. La idea es justamente esa: que se sumen al ritmo de la vida de campo, a nuestro tiempo y nuestras costumbres.",
      queHaremos: "Te recibiremos con una sonrisa sincera y contaremos sobre las actividades que compartiremos. Estas varían con las estaciones y el ritmo del día, y pueden incluir alimentar y mimar a nuestros animales (las traviesas cabras, las gallinas y nuestros fieles perros), participar en las labores agrícolas, sintiendo la tierra entre tus manos, o colaborar en tareas domésticas tradicionales, como preparar una receta local llena de sabor e historia.\n\nAl finalizar, nos sentaremos juntos a la mesa para compartir un refrigerio para recargar energías.",
      incluye: ["Refrigerio para recargar energías."],
      dificultadDetalle: "Bajo. Esta experiencia es ideal para quienes desean desconectar y disfrutar de la vida de campo, el trabajo con la tierra, las plantas y los animales. No necesitan saber nada de antemano, yo les guiaré con paciencia en cada paso. Sí, tengan en cuenta que estarán en contacto con la tierra y que esta se puede adherir a tus uñas y ropa.",
      img: "images/estrellafamiliar/vidarural1.jpeg", imgGal1: "images/maices.jpeg", imgGal2: "images/maices.jpeg", imgGal3: "images/maices.jpeg",
    },
    {
      id: "es-2", emprendimiento: "estrella",
      titulo: "Día en la casa", subtitulo: "Mañana completa con almuerzo familiar",
      duracion: "De 10:00 a 14:00 hs aprox.", grupo: "De 1 a 6 personas", dificultad: "Bajo", categoria: "rural",
      descripcion: "Una jornada completa para sumergirse en el ritmo de la vida de campo: animales, huerta, tareas domésticas y mesa familiar. Se siente de verdad cómo se vive en este rincón de la Quebrada.",
      queHaremos: "Compartiremos las tareas de la mañana —animales, huerta, alguna receta— y luego nos sentaremos todos juntos a la mesa para un almuerzo familiar con sabores puros y directos de lo que producimos en casa.",
      incluye: ["Refrigerio.", "Almuerzo familiar."],
      dificultadDetalle: "Bajo. Sin experiencia previa necesaria, te guiaré con paciencia en cada paso.",
      img: "images/estrellafamiliar/casa1.jpeg", imgGal1: "images/maices.jpeg", imgGal2: "images/maices.jpeg", imgGal3: "images/maices.jpeg",
    },
    {
      id: "es-3", emprendimiento: "estrella",
      titulo: "Tardes con mate", subtitulo: "Merienda y vida andina",
      duracion: "De 14:00 a 18:00 hs aprox.", grupo: "De 1 a 6 personas", dificultad: "Bajo", categoria: "rural",
      descripcion: "Una tarde tranquila en la casa: cabras, gallinas, huerta y mate. Ideal para quienes buscan un descanso activo, lejos del bullicio.",
      queHaremos: "Sumate a las tareas de la tarde y a la mesa para una merienda reconfortante con productos de la casa.",
      incluye: ["Una reconfortante merienda."],
      dificultadDetalle: "Bajo.",
      img: "images/estrellafamiliar/merienda1.jpeg", imgGal1: "images/maices.jpeg", imgGal2: "images/maices.jpeg", imgGal3: "images/maices.jpeg",
    },
    {
      id: "es-4", emprendimiento: "estrella",
      titulo: "Estadía con Alojamiento", subtitulo: "Vivir el atardecer maimareño",
      duracion: "Desde las 13:00 hs", grupo: "De 1 a 6 personas", dificultad: "Bajo", categoria: "rural",
      descripcion: "Para quienes quieren desconectar unos días y sentir de verdad cómo se vive en este rincón de la Quebrada. Habitaciones sencillas pero cómodas.",
      queHaremos: "Te esperamos alrededor de las 13:00 hs para almorzar juntos. Luego, te instalarás en una habitación y serás parte de las actividades rurales de la tarde, viviendo el atardecer desde nuestro rincón del mundo.",
      incluye: ["Almuerzo familiar.", "Alojamiento.", "Actividades rurales de la tarde."],
      dificultadDetalle: "Bajo.",
      img: "images/estrellafamiliar/estadia1.jpeg", imgGal1: "images/maices.jpeg", imgGal2: "images/maices.jpeg", imgGal3: "images/maices.jpeg",
    },

    {
      id: "mt-1", emprendimiento: "manitos",
      titulo: "Del vellón al hilo", subtitulo: "Primeros pasos del tratamiento de la fibra",
      duracion: "De 4 a 5 horas aprox.", grupo: "De 1 a 6 personas", dificultad: "Bajo", categoria: "textil",
      descripcion: "El camino de un textil inicia con la esquila. Como en la zona de Quebrada, donde vivo actualmente, no hay rebaños de ovejas, yo misma selecciono y adquiero cueros de los criadores para esquilar y desmotar, formando vellones de lana. Luego, esos vellones se transforman en hilos, ya sea utilizando la puisca —un huso de origen prehispánico— o la hiladora a pedal, llamada rueca.\n\nEsta experiencia está diseñada para guiarles en los primeros pasos del tratamiento de la fibra, permitiéndoles familiarizarse con el proceso y elaborar su propio hilo, el primer eslabón para crear, en el futuro, una prenda única.",
      queHaremos: "Les recibiré en mi casa, donde nos instalaremos en un espacio cómodo y con buena luz natural. Comenzaremos equipándonos con delantal, antiparras y barbijos para luego limpiar y desmotar la lana, dando forma a los vellones. Después, transformaremos esos vellones en hilos utilizando el método que prefieran: la tradicional puisca o la práctica rueca a pedal.\n\nHaremos una pausa para compartir un refrigerio tradicional, caliente o refrescante, según el clima y sus preferencias. En este momento, también podrán apreciar y probarse otras prendas y souvenirs que tengo disponibles para la venta. Retomaremos la actividad y, al finalizar, cada participante se llevará como recuerdo el hilo que logró hilar con sus propias manos.",
      incluye: ["Un refrigerio tradicional, caliente o refrescante, adaptado al clima y sus preferencias.", "Una madeja de hilo en fibra de llama u oveja, elaborada por ustedes durante la experiencia.", "Todos los materiales necesarios para realizar la actividad."],
      dificultadDetalle: "Bajo. Esta experiencia está dirigida a todas las personas interesadas en el mundo textil. No se requiere conocimiento previo, ya que les guiaré en cada paso. Eso sí, es posible que durante la limpieza de la lana alguna partícula de tierra se adhiera a las uñas, o que el aroma natural de la lana impregne levemente la ropa.",
      img: "images/manitostejedoras/hilo1.jpg", imgGal1: "images/manitostejedoras/hilo2.jpeg", imgGal2: "images/manitostejedoras/hilo3.jpeg", imgGal3: "images/manitostejedoras/hilo4.jpg",
    },
    {
      id: "mt-2", emprendimiento: "manitos",
      titulo: "Alquimia del color", subtitulo: "Tintes naturales",
      duracion: "De 4 a 5 horas", grupo: "De 1 a 6 personas", dificultad: "Medio", categoria: "textil",
      descripcion: "Teñir lanas es una alquimia compleja y fascinante. Para dominar este arte, es necesario conocer las plantas y sus propiedades, las épocas adecuadas para recolectarlas, los procesos de preparación, los mordientes que fijan los colores, y los tiempos precisos de hervor y reposo. Además, se requiere un espacio preparado con fogón, tachos y áreas para el secado.\n\nLos invito a incursionar en esta magia ancestral, donde transformaremos ingredientes naturales en una paleta de colores vivos y llenos de significado.",
      queHaremos: "Al llegar, comenzaremos con una charla donde explicaré los secretos y detalles de este arte milenario. Aprovecharemos este momento para compartir un refrigerio tradicional, que nos preparará para la experiencia.\n\nSi nos visitan en una época propicia, nos acercaremos a la quebrada para recolectar juntos las plantas que usaremos. De lo contrario, trabajaremos con ingredientes que ya tengo recolectados y tratados.\n\nUna vez equipados, iniciaremos el proceso: encenderemos el fogón, prepararemos los baños de color en los tachos y aplicaremos los mordientes para fijar los tintes en las lanas. Después del tiempo necesario de reposo, tenderemos las madejas teñidas para que sequen naturalmente.\n\nComo recompensa por haber sido parte de esta transformación, cada participante recibirá un souvenir especial confeccionado por Manitos Tejedoras.",
      incluye: ["Refrigerio tradicional (caliente o refrescante, de acuerdo al clima y sus preferencias).", "Un souvenir confeccionado por Manitos Tejedoras.", "Todos los materiales e ingredientes necesarios para la actividad."],
      dificultadDetalle: "Medio. Esta experiencia requiere seguir instrucciones y participar en un proceso de varias etapas, una de las cuales involucra encender un fogón y poner a hervir en un tacho, agua y plantas para luego remojar la lana. Es ideal para quienes desean conectar con la naturaleza y los saberes ancestrales a través de la práctica.",
      img: "images/manitostejedoras/tintes1.jpeg", imgGal1: "images/manitostejedoras/tintes2.jpeg", imgGal2: "images/manitostejedoras/tintes3.jpeg", imgGal3: "images/manitostejedoras/tintes4.jpeg",
    },
    {
      id: "mt-3", emprendimiento: "manitos",
      titulo: "Primeras tramas", subtitulo: "Tejido en telar bastidor",
      duracion: "4 horas", grupo: "De 1 a 6 personas", dificultad: "Bajo", categoria: "textil",
      descripcion: "Urdir un telar es un arte, un momento especial donde los hilos se ordenan y tensan para dar vida a un textil. En esta experiencia, pondrás tus manos en el telar bastidor, la herramienta que te permitirá dar forma a tu propia creación. Guiado por mí, aprenderás los fundamentos de esta técnica y darás los primeros pasos para crear una pieza tejida con tus propias manos.",
      queHaremos: "Te recibiré en mi taller para iniciar este viaje textil. Comenzaremos con el proceso de urdido, donde aprenderás a colocar y tensar los hilos en el telar bastidor, formando la base de tu tejido. Una vez armado el telar, te guiaré en los pasos necesarios para crear tus primeras tramas.\n\nHaremos una pausa para disfrutar de un refrigerio tradicional, momento ideal para absorber lo aprendido y admirar el avance de tu trabajo.\n\nAl finalizar, no te llevarás solo un recuerdo, sino el telar bastidor con tu trabajo iniciado, para que puedas continuar tejiendo y practicando en tu hogar, llevando contigo una parte viva de esta tradición.",
      incluye: ["Todos los materiales necesarios para la experiencia.", "Un refrigerio tradicional (caliente o refrescante, según clima y preferencias).", "El telar bastidor con tu trabajo iniciado para llevar a casa."],
      dificultadDetalle: "Bajo. Esta actividad está dirigida a todas las personas interesadas en el mundo textil. No se necesita conocimiento previo, pues te guiaré paso a paso en cada etapa. Es posible que el aroma natural de la lana impregne levemente tus manos y ropa durante el proceso.",
      img: "images/manitostejedoras/telar1.jpeg", imgGal1: "images/manitostejedoras/telar2.jpeg", imgGal2: "images/manitostejedoras/telar3.jpeg", imgGal3: "images/manitostejedoras/telar4.jpeg",
    },

    {
      id: "qu-1", emprendimiento: "qullana",
      titulo: "Alquimia vegetal: obtené tu propio aceite esencial",
      subtitulo: "Destilamos un aceite esencial",
      duracion: "3 horas aprox. (puede variar)", grupo: "De 1 a 3 personas", dificultad: "Medio", categoria: "herbolaria",
      descripcion: "La destilación de un aceite esencial por arrastre de vapor es un método muy antiguo que permite extraer compuestos aromáticos de plantas medicinales usando vapor de agua, sin quemarlos ni descomponerlos.\n\nEn un dispositivo llamado alambique, el vapor de agua atraviesa el material vegetal (hojas, flores, tallos, raíces), arrastra los compuestos volátiles (el aceite esencial) y luego todo se condensa para separar el aceite del agua. Así se obtiene una medicina de alta calidad que puede ser utilizada de diversas formas.",
      queHaremos: "Elaboraremos un aceite esencial por medio de la técnica de «arrastre por vapor».\n\nLos visitantes serán recibidos en mi laboratorio artesanal. Les contaré brevemente acerca de los procesos del laboratorio y los diferentes tipos de medicinas que podrán apreciar en el lugar.\n\nLuego procederemos a preparar la planta (depende de la temporada del año variaremos el material vegetal) para su proceso de destilación. Aprenderán la técnica de principio a fin, pudiendo llevarse un frasco de hidrolato medicinal y las indicaciones sobre cómo utilizarlo.\n\nCompartiremos mates o una bebida refrescante, de acuerdo al momento del año. También podrán acceder a un showroom con productos a la venta.",
      incluye: ["Un refrigerio.", "Todos los materiales necesarios para realizar la actividad.", "Un producto artesanal que se llevarán de regalo, preparado por ellos mismos.", "Un pequeño instructivo digital sobre el uso de los aceites esenciales e hidrolatos."],
      dificultadDetalle: "Media. Esta actividad es ideal para aquellas personas que disfrutan del contacto con las plantas. Si bien el uso del alambique puede parecer complejo, no es necesario tener conocimientos previos, ya que serán guiados y les acompañaré en todo el proceso hasta obtener el hidrolato.",
      img: "images/qullana/aceite1.jpeg", imgGal1: "images/maices.jpeg", imgGal2: "images/maices.jpeg", imgGal3: "images/maices.jpeg",
    },
    {
      id: "qu-2", emprendimiento: "qullana",
      titulo: "La medicina está en tus manos",
      subtitulo: "Ungüentos, pomadas y tinturas madre",
      duracion: "1.5 a 2 horas", grupo: "De 1 a 3 personas", dificultad: "Bajo", categoria: "herbolaria",
      descripcion: "Desde tiempos ancestrales, nuestras abuelas han preparado ungüentos, pomadas y macerados herbales para aliviar diferentes sintomatologías. Esta medicina casera es fácil de hacer y sirve para aliviar y tratar afecciones de forma natural.\n\nAsí, se combinan grasas o ceras (como aceite o cera de abeja) y alcohol con plantas medicinales (caléndula, árnica, manzanilla, etc.) para obtener una medicina familiar de calidad.",
      queHaremos: "Elaboraremos una pomada medicinal y una tintura madre desde cero, aprenderemos sobre fórmulas, usos y versatilidad de materiales para realizarlas.\n\nLos visitantes serán recibidos en mi laboratorio artesanal. Les contaré brevemente acerca de los procesos del laboratorio y los diferentes tipos de medicinas que podrán apreciar en el lugar.\n\nLuego procederemos a conocer los ingredientes que utilizaremos para elaborar la pomada, más otras alternativas. Prepararemos una pomada y una tintura madre a base de ingredientes naturales y hablaremos sobre sus posibles usos medicinales.\n\nCompartiremos mates o una bebida refrescante, de acuerdo al momento del año. También podrán acceder a un showroom con productos a la venta.",
      incluye: ["Un refrigerio.", "Todos los materiales necesarios para realizar la actividad.", "Dos productos artesanales que se llevarán de regalo, preparado por ellos mismos.", "Un pequeño instructivo digital sobre el uso de pomadas, cremas medicinales y tinturas madre."],
      dificultadDetalle: "Bajo. Pueden realizar esta actividad todas aquellas personas que disfruten el contacto y aprender de las propiedades de las plantas. No se necesita conocimiento o preparación previa, pues yo les iré guiando en cada paso hasta obtener la pomada y la tintura madre.",
      img: "images/qullana/medicina1.jpeg", imgGal1: "images/maices.jpeg", imgGal2: "images/maices.jpeg", imgGal3: "images/maices.jpeg",
    },

    {
      id: "al-1", emprendimiento: "alborada",
      titulo: "Bordado de flores", subtitulo: "El sello personal de Nora",
      duracion: "3 horas", grupo: "De 1 a 6 personas", dificultad: "Bajo", categoria: "textil",
      descripcion: "El textil es todo un mundo. Si hay un inicio, tendríamos que remontarnos hasta la cría de los animales que proveen la fibra. Una vez al año, se lleva a cabo la esquila y la fibra debe ser tratada inmediatamente para asegurar su calidad. Luego se la hila, muchas veces en puisca (huso de origen prehispánico). Cuando se transforma en hilo, el proceso continúa, pues se le puede dar colores, trabajarlo en telar, en bastidores, confeccionar telas que deriven en prendas, adornos, suvenires, sogas y lo que la imaginación pueda crear.\n\nMi actividad como artesana se ubica en este punto, confecciono prendas de vestir, accesorios y objetos de decoración. Pero la parte que más disfruto y quiero compartir es el detalle final de estos trabajos, el bordado. Mi sello personal son coloridas flores que bordo con mucha paciencia, dedicación y amor en los productos que ofrezco.",
      queHaremos: "Les recibiré en mi casa, les daré la bienvenida y proveeré una cajita costurero con los materiales necesarios para llevar a cabo un bordado en un suvenir o en una prenda textil confeccionados por mí. Les iré guiando paso a paso y compartiré mis técnicas para lograr un hermoso bordado.\n\nLuego de una hora de trabajo, tendremos un tiempo de descanso en el que compartiremos una bebida tradicional refrescante y podrán apreciar y probarse otras prendas y suvenires que tengo para la venta. Retomaremos la tarea y al finalizar podrá llevarse una prenda o suvenir bordado con sus propias manos.",
      incluye: ["Una bebida tradicional, caliente o refrescante.", "Un souvenir (cartuchera, sobre necesaire o monedero).", "Material para llevar a cabo el bordado.", "Opcional: si desean llevar a cabo el bordado sobre una prenda textil, pueden hacerlo abonando la diferencia en el precio de la misma."],
      dificultadDetalle: "Bajo. Pueden realizar esta actividad todas aquellas personas que se sientan atraídas por el mundo del textil y del bordado. Si bien no se necesita algún conocimiento o preparación previa pues les iré guiando en cada paso, es posible que la actividad no sea adecuada para quienes tienen dificultades de visión o en el pulso.",
      img: "images/alborada/exp2.jpeg", imgGal1: "images/maices.jpeg", imgGal2: "images/maices.jpeg", imgGal3: "images/maices.jpeg",
    },
    {
      id: "al-2", emprendimiento: "alborada",
      titulo: "Adornos con flores de lana", subtitulo: "La tradición de «florar» el ganado",
      duracion: "1 hora", grupo: "De 1 a 6 personas", dificultad: "Bajo", categoria: "textil",
      descripcion: "En el campo, una de las tradiciones más significativas es «florar» el ganado: un acto fundamental dentro de la ceremonia más amplia de la marcada o señalada. Esta práctica no es solo decorativa; es una invocación a la fertilidad y una renovación del ciclo de la vida.\n\nEn esta experiencia, recrearemos la técnica ancestral para confeccionar esas flores de lana de colores vibrantes que usamos en esa ocasión. Mientras creamos con nuestras manos, conversaremos sobre el profundo significado de esta tradición.\n\nAl finalizar, transformaremos nuestras flores en un objeto cargado de significado: un llavero o un adorno para cortinas o puertas. Así, podrán llevar consigo un fragmento de esta cosmovisión a su hogar.",
      queHaremos: "Les recibiré, compartiré el significado de las flores y los usos tradicionales que tienen. Les proveeré todos los materiales y les guiaré paso a paso en la técnica para crear sus propias flores de lana, compartiendo mis secretos artesanales.\n\nJuntos transformaremos las flores en un llavero o adorno único. Para cerrar, disfrutaremos de un tiempo de descanso con una bebida tradicional refrescante, donde podrán apreciar y probarse otras prendas y suvenires de mi autoría que tengo disponibles.",
      incluye: ["Una bebida tradicional, caliente o refrescante.", "Un souvenir (llavero).", "Material para llevar a cabo el llavero."],
      dificultadDetalle: "Bajo. Pueden realizar esta actividad todas aquellas personas que se sientan atraídas por el mundo del textil. Si bien no se necesita algún conocimiento o preparación previa pues les iré guiando en cada paso, es posible que la actividad no sea adecuada para quienes tienen dificultades de visión o en el pulso.",
      img: "images/alborada/exp1.jpeg", imgGal1: "images/maices.jpeg", imgGal2: "images/maices.jpeg", imgGal3: "images/maices.jpeg",
    },
    {
      id: "al-3", emprendimiento: "alborada",
      titulo: "El circuito del textil", subtitulo: "De la fibra a la prenda",
      duracion: "2 horas", grupo: "De 2 a 12 personas", dificultad: "Bajo", categoria: "textil",
      descripcion: "Imagina seguir el viaje de una hebra de lana desde el momento en que es esquilada hasta convertirse en una prenda colorida, cargada de historia e identidad.\n\nTe invitamos a ser parte de esta transformación en una experiencia que despierta los sentidos y conecta con el corazón artesanal de la Puna.\n\nA través de una muestra interactiva, recorreremos las distintas etapas por las que atraviesa la fibra hasta convertirse en un producto terminado. Tejidos Alborada les permitirá conocer y experimentar algunos de los procesos fundamentales que forman parte de la transformación de la lana en artesanías textiles.",
      queHaremos: "Les recibiremos en nuestro taller con una bienvenida e introducción a la historia del emprendimiento y su vínculo con la tradición textil andina.\n\nLuego, organizados en grupos reducidos, recorreremos cuatro estaciones donde podrán conocer y apreciar en detalle cada etapa del proceso: desde la fibra recién obtenida hasta la prenda terminada. En cada sector compartiremos saberes, técnicas y secretos del trabajo artesanal, permitiéndoles observar y participar en algunos momentos del proceso.\n\nPara cerrar el encuentro, compartiremos un refrigerio elaborado con ingredientes típicos de la región, generando un espacio distendido para conversar y hacer preguntas. Al finalizar el recorrido, podrán apreciar, probarse prendas y conocer los souvenirs textiles disponibles para la venta.",
      incluye: ["Un refrigerio elaborado con ingredientes tradicionales de la región.", "Un souvenir (llavero o adorno colgante de pompones de fibra de llama u oveja)."],
      dificultadDetalle: "Bajo. Pueden realizar esta actividad todas aquellas personas que se sientan atraídas por el mundo del textil. No se necesita conocimiento o preparación previa, ya que les guiaremos en cada paso.",
      img: "images/alborada/exp3.jpeg", imgGal1: "images/maices.jpeg", imgGal2: "images/maices.jpeg", imgGal3: "images/maices.jpeg",
    },

    {
      id: "tm-1", emprendimiento: "tierramia",
      titulo: "Visita al campo de flores", subtitulo: "Saberes de 30 años de cultivo",
      duracion: "1 hora", grupo: "De 1 a 10 personas", dificultad: "Bajo", categoria: "agricola",
      descripcion: "Contemplar un campo sembrado de flores u hortalizas es una satisfacción profunda, pues es reflejo de un trabajo constante y amoroso. Las flores, en particular, son un cultivo de paciencia: su ciclo, desde la semilla hasta la cosecha, lleva de siete a ocho meses. Ponemos los almácigos en abril o mayo, para plantar en agosto cuando bajan las heladas, y la cosecha comienza entre noviembre, diciembre y abril, entre Pascuas y Todosantos.\n\nPero esa belleza es un logro. Las flores son delicadas y exigen cuidado permanente contra hongos, ácaros y arañuelas; si estas últimas avanzan, llega la temible roya. Todo depende de nutrir la tierra con esmero: realizamos tres abonadas tras el trasplante para obtener una producción vigorosa y abundante.\n\nEl secreto de la tierra sana está en la rotación. Sembrar siempre flores agota el suelo y atrae hongos; alternar con cebolla o ajo lo limpia y fortalece. La agricultura, al final, es una lección de vida: hay años buenos para las flores y años difíciles; entonces, son las hortalizas las que sostienen el hogar. Así, diversificando, la tierra y la familia salen adelante.\n\nEn este recorrido, compartiremos no solo saberes sobre el cultivo de flores y hortalizas, sino también historias de vida y familia, cosechando hermosos recuerdos.",
      queHaremos: "A su llegada, les daré la bienvenida y brindaré las recomendaciones para realizar el recorrido. Nos aproximaremos a las parcelas sembradas para observar con atención a las plantas en diferentes etapas de su crecimiento. Podrán tomar fotografías y consultar sobre lo relativo a su cultivo. Si están maduras, cortaremos algunas. Si aún no es tiempo, podremos apreciar algunas variedades secas, como solemos conservarlas.\n\nPara finalizar, compartiremos un refrigerio tradicional, caliente o refrescante, según el clima.",
      incluye: ["Un refrigerio tradicional, caliente o refrescante."],
      dificultadDetalle: "Bajo. Pueden realizar esta actividad todas aquellas personas que deseen aproximarse y conocer más sobre el cultivo de flores y hortalizas. La propuesta implica un recorrido en torno a las plantaciones por senderos de tierra bajo la guía de Patricia.",
      img: "images/tierramia/flores1.jpeg", imgGal1: "images/tierramia/flores2.jpeg", imgGal2: "images/tierramia/flores3.jpeg", imgGal3: "images/tierramia/flores4.jpeg",
    }
  ],

  categorias: [
    { id: "todas", label_es: "Todas", label_en: "All" },
    { id: "gastronomia", label_es: "Gastronomía", label_en: "Food" },
    { id: "textil", label_es: "Textil", label_en: "Textile" },
    { id: "rural", label_es: "Vida rural", label_en: "Rural life" },
    { id: "herbolaria", label_es: "Herbolaria", label_en: "Herbalism" },
    { id: "agricola", label_es: "Agrícola", label_en: "Agricultural" },
    { id: "sustentabilidad", label_es: "Sustentabilidad", label_en: "Sustainability" }
  ],

  faqs: [
    { q_es: "¿Cómo reservo una experiencia?", q_en: "How do I book an experience?",
      a_es: "Elegí la experiencia que quieras y contactá por WhatsApp al anfitrión/a. Indicá cantidad de personas y fecha estimada. El anfitrión te dará los detalles (horarios, duración, precio). La reserva se confirma al coordinar día y pagar la seña. En caso de demora en la respuesta, recomendamos llamar por teléfono.",
      a_en: "Choose your experience, contact the host via WhatsApp, share the group size and an estimated date. Booking confirms when day is set and deposit paid." },
    { q_es: "¿Es necesario tener experiencia previa?", q_en: "Do I need prior experience?",
      a_es: "No, las experiencias están diseñadas para todo público, no se necesita experiencia previa. Todas las actividades están pensadas para aprender compartiendo, paso a paso.",
      a_en: "No. Experiences are designed for everyone — learn by sharing, step by step." },
    { q_es: "¿Cómo puedo pagar?", q_en: "Payment methods?",
      a_es: "Cada anfitrión lo organiza distinto, pero generalmente aceptan efectivo y transferencia bancaria.",
      a_en: "Each host arranges it differently, but generally cash and bank transfer." },
    { q_es: "¿Cuánto duran las actividades?", q_en: "How long are activities?",
      a_es: "Varía según la propuesta: entre 2 y 3 horas, o media jornada. Te recomendamos contar siempre con tiempo para disfrutar sin apuros.",
      a_en: "Varies: 2–3 hours or half a day. Always plan extra time to enjoy unhurried." },
    { q_es: "¿Qué debo llevar?", q_en: "What should I bring?",
      a_es: "Ropa y calzado cómodos, gorro, protector solar y agua. Y lo más importante: ¡ganas de compartir!",
      a_en: "Comfortable clothes and shoes, hat, sunscreen, water. And willingness to share!" },
    { q_es: "¿Se incluyen comidas en las experiencias?", q_en: "Are meals included?",
      a_es: "En algunas sí, como en Inti Pacha; en otras se ofrece un desayuno/merienda sencillo. Te recomendamos consultar directamente con cada anfitrión.",
      a_en: "Some yes (Inti Pacha), others offer a simple snack. Best to check with each host." },
    { q_es: "¿Las experiencias son aptas para niños?", q_en: "Are experiences kid-friendly?",
      a_es: "Sí. Muchas experiencias son familiares y los niños disfrutan mucho en la huerta, con los animales o en los talleres. Algunas son más adecuadas que otras para familias con niños, consulta con nosotros.",
      a_en: "Yes. Many are family-friendly. Some suit kids better than others — ask us." }
  ],

  i18n: {
    nav_home: { es: "Inicio", en: "Home" }, nav_about: { es: "Sobre el grupo", en: "About us" },
    nav_exp: { es: "Experiencias", en: "Experiences" }, nav_hosts: { es: "Anfitriones", en: "Hosts" },
    nav_gallery: { es: "Galería", en: "Gallery" }, nav_visit: { es: "Cómo llegar", en: "How to get here" },
    nav_contact: { es: "Contacto", en: "Contact" },
    book: { es: "Reservar", en: "Book" }, duration: { es: "Duración", en: "Duration" },
    group: { es: "Grupo", en: "Group size" }, difficulty: { es: "Dificultad", en: "Difficulty" },
    includes: { es: "Incluye", en: "Includes" }, location: { es: "Ubicación", en: "Location" },
    hosts: { es: "Anfitriones", en: "Hosts" }, schedule: { es: "Horarios", en: "Hours" },
    payment: { es: "Pagos", en: "Payment" }, contact: { es: "Contacto", en: "Contact" },
    description: { es: "Descripción", en: "Description" }, what: { es: "Qué haremos", en: "What we'll do" },
    diff_detail: { es: "Sobre la dificultad", en: "About difficulty" }
  }
};
